### ISSUE TITLE
运行executable.jar 报ArkConfigs  NoClassDefFoundError 异常

### ISSUE THREAD

**Issue by jjj124** [sofastack-guides/spring-boot-ark-biz#3]
<properties>
        <java.version>1.8</java.version>
        <sofa.ark.version>2.0.0</sofa.ark.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.12</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.alipay.sofa</groupId>
                <artifactId>sofa-ark-maven-plugin</artifactId>
                <version>${sofa.ark.version}</version>
                <executions>
                    <execution>
                        <id>default-cli</id>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <skipArkExecutable>false</skipArkExecutable>
                    <outputDirectory>./target</outputDirectory>
                    <bizName>plugin-ark-biz</bizName>
                    <webContextPath>biz</webContextPath>
                </configuration>
            </plugin>
        </plugins>
    </build>

**Comment by jjj124** [comment]
<sofa.ark.version>2.0.0</sofa.ark.version>
使用2.0.0 版本

**Comment by jjj124** [comment]
public Object launch(String[] args) throws Exception {
        if (!ArkConfigs.isEmbedEnable()) {
            JarFile.registerUrlProtocolHandler();
        }
        ClassLoader classLoader = createContainerClassLoader(getContainerArchive());
        List<String> attachArgs = new ArrayList<>();
        attachArgs
            .add(String.format("%s%s=%s", CommandArgument.ARK_CONTAINER_ARGUMENTS_MARK,
                CommandArgument.FAT_JAR_ARGUMENT_KEY, getExecutableArchive().getUrl()
                    .toExternalForm()));
        attachArgs.addAll(Arrays.asList(args));
        return launch(attachArgs.toArray(new String[attachArgs.size()]), getMainClass(),
            classLoader);
    }

发现ArkConfigs 这个类没有被打包在根目录

**Comment by lvjing2** [comment]
麻烦拉下最新代码试下，感谢。
